server {
	listen 80;
	listen [::]:80;
    server_name node56-be.vulebaolong.com;
    return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
	listen [::]:443 ssl;

    server_name node56-be.vulebaolong.com;

    ssl_certificate /etc/nginx/ssl/vulebaolong.com.crt;
    ssl_certificate_key /etc/nginx/ssl/vulebaolong.com.key;

	location / {
        proxy_pass http://0.0.0.0:3070;
        include proxy_params;
	}
}
